### ISSUE TITLE
NPM is saying it's been renamed to @rimiti/stimmy

### ISSUE THREAD

**Issue by rustinlewis** [rimiti/stimmy#7]
npm install stimmy --save is saying it's been renamed to @rimiti/stimmy.  

In order to install the newest version I had to install @rimiti/stimmy --save ... then you have to:

const stimmy = require('@rimiti/stimmy');

**Comment by rimiti** [comment]
Holy shit... It's because I've moved this packages into @rimiti namespaces.
It has been fixed, thank you !

Have a nice coding day ;)
Regards,
